sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn clean package -Dmaven.test.skip=true
  - docker build -t gravitant/coreapi-provider .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
  - docker push gravitant/coreapi-provider